# Generated by Django 5.1.7 on 2025-04-17 17:46

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('account', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='profile',
            name='avatar',
            field=models.ImageField(blank=True, default='/avatars/washing_machine.jpg', upload_to='avatars/'),
        ),
    ]
